---
- name: Create Prometheus system group
  group:
    name: prometheus
    system: yes
    state: present

- name: Create Prometheus system user
  user:
    name: prometheus
    system: yes
    group: prometheus
    create_home: no
    shell: /sbin/nologin

- name: Create Prometheus directories
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'
  loop:
    - /etc/prometheus
    - /var/lib/prometheus

- name: Download Prometheus
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
  register: prometheus_download
  when: not ansible_check_mode  # Skip this task in dry-run mode

- name: Unarchive Prometheus
  unarchive:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: /tmp
    remote_src: yes
  when: prometheus_download.changed and not ansible_check_mode  # Run only if download happened and not in dry-run mode

- name: Copy Prometheus binary
  copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/prometheus"
    dest: /usr/local/bin/prometheus
    owner: prometheus
    group: prometheus
    mode: '0755'
    remote_src: yes
  when: not ansible_check_mode  # Skip in dry-run mode

- name: Copy Prometheus configuration
  template:
    src: prometheus.yaml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: '0644'
  notify: Restart Prometheus

- name: Install Prometheus systemd service
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
    mode: '0644'
  notify: Restart Prometheus

- name: Ensure Prometheus is started and enabled
  systemd:
    name: prometheus
    state: started
    enabled: yes
    daemon_reload: yes
