---
- hosts: all
  ignore_unreachable: yes
  gather_facts: true
  roles:
    - role: ufw
      vars:
        ufw_allowed_ports: 
          - "22"
          - "80"
          - "443"
          - "9090"
        ufw_logging: 'on'
    - role: prometheus
      become: true
      vars:
        prometheus_version: "2.38.0"
        prometheus_storage_retention: "30d"
        prometheus_scrape_configs:
          - job_name: 'prometheus'
            static_configs:
              - targets: ['localhost:9090']
