- hosts: all
  gather_facts: false
  tasks:
    - name: Ping the host to check reachability
      ping:
      ignore_unreachable: yes
      register: ping_result

    - name: Skip unreachable hosts
      meta: end_play
      when: ping_result.unreachable is defined or ping_result.ping is not defined or ping_result.ping != "pong"
  roles:
    - role: ufw
      vars:
        ufw_allowed_ports: 
          - "22"
          - "80"
          - "443"
          - "9090"
        ufw_logging: 'on'
    - role: prometheus
      vars:
        prometheus_version: "2.38.0"
        prometheus_storage_retention: "30d"
        prometheus_scrape_configs:
          - job_name: 'prometheus'
            static_configs:
              - targets: ['localhost:9090']