---
- name: Apache installation with custom message setup and conditionally install htop
  hosts: all
  become: yes
  vars:
    custom_message: "{{ lookup('env', 'CUSTOM_MESSAGE') }}"
    install_htop: "{{ lookup('env', 'INSTALL_HTOP') }}"

  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Ensure Apache is running and enabled at boot
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Create custom index.html with a message
      copy:
        content: "<html><body><h1>{{ custom_message }}</h1></body></html>"
        dest: /var/www/html/index.html
        mode: '0644'
    
    - name: Conditionally install htop if requested
      apt:
        name: htop
        state: present
      when: install_htop == "yes"